# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box      = 'ubuntu1304'
  config.vm.hostname = 'dokku-box'

  config.vm.provision :shell, :inline => 'wget -qO- https://raw.github.com/progrium/dokku/master/bootstrap.sh | sudo bash'
end
