# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box      = 'centos64'
  config.vm.hostname = 'php-build-box'

  config.vm.provision :puppet do |puppet|
    puppet.options = ['--templatedir', '/vagrant/templates']
  end
end
